#!/bin/bash

# TODO: Obsolete hardcoded path.
if [[ $PWD != $RSYNCED* ]]; then
	echo "WARN: rsyarn only works under rsynced directory: $RSYNCED"
	exit 1
fi

pkg_prev=$(md5sum package.json)
lock_prev=$(md5sum yarn.lock)

yarn "$@"

pkg_current=$(md5sum package.json)
lock_current=$(md5sum yarn.lock)

if [ "$pkg_current" != "$pkg_prev" ] || [ "$lock_current" != "$lock_prev" ]; then
	echo "INFO: File(s) have changed."

	cp package.json yarn.lock /vboxsf$PWD/

	if [ $? -eq 0 ]; then
		echo "INFO: Successfully copied to: /vboxsf$PWD/"
	else
		echo "FAIL: Failed to copy files."
		exit 1
	fi
else
	echo "INFO: Files have not changed."
fi
